name: Deploy Application with VPN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IIS_SHARE: '\\\\iis-201.wmi.amu.edu.pl\\s473603\\public_iis'
      OFFLINE_FILE: 'app_offline.htm'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create OpenVPN Config File
        run: |
          echo "${{ secrets.OPEN_VPN_CONFIG }}" | base64 --decode > vpn-config.ovpn

      - name: Install OpenVPN
        run: sudo apt-get install -y openvpn

      - name: Create temporary file for VPN credentials
        run: |
          echo -e "${{ secrets.OPEN_VPN_LOGIN }}\n${{ secrets.OPEN_VPN_PASSWORD }}" > /tmp/vpn-credentials.txt

      - name: Connect to VPN
        run: |
          sudo openvpn --config vpn-config.ovpn --auth-user-pass /tmp/vpn-credentials.txt --daemon

      - name: Verify VPN Connection
        run: curl ifconfig.me

      - name: Install SMB Client Utilities
        run: sudo apt-get install -y cifs-utils

      - name: Mount SMB Share
        run: |
          sudo mount -t cifs //$IIS_SHARE /mnt/share -o username=${{ secrets.IIS_LOGIN }},password=${{ secrets.IIS_PASSWORD }}
          echo 'Application offline for maintenance' > /mnt/share/$OFFLINE_FILE

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release

      - name: Publish Application
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy to Network Share
        run: |
          sudo cp -r ./publish/* /mnt/share/
        
      - name: Unmount SMB Share
        run: sudo umount /mnt/share

      - name: Cleanup
        run: |
          sudo rm /mnt/share/$OFFLINE_FILE

      - name: Clean Up VPN Config File
        run: rm -f vpn-config.ovpn
