name: Deploy Application with VPN

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IIS_SHARE: 'iis-2019.wmi.amu.edu.pl/s473603/public_iis'
      OFFLINE_FILE: 'app_offline.htm'
      CONNECTION_STRING: ${{ secrets.CONNECTION_STRING_WMI }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create OpenVPN Config File
        run: |
          echo "${{ secrets.OPEN_VPN_CONFIG }}" | base64 --decode > vpn-config.ovpn

      - name: Install OpenVPN
        run: sudo apt-get install -y openvpn

      - name: Create temporary file for VPN credentials
        run: |
          echo -e "${{ secrets.OPEN_VPN_LOGIN }}\n${{ secrets.OPEN_VPN_PASSWORD }}" > /tmp/vpn-credentials.txt

      - name: Connect to VPN
        run: |
          sudo openvpn --config vpn-config.ovpn --auth-user-pass /tmp/vpn-credentials.txt --daemon

      - name: Verify VPN Connection
        run: curl ifconfig.me

      - name: Install SMB Client Utilities
        run: sudo apt-get install -y cifs-utils

      - name: Create Mount Directory
        run: sudo mkdir -p /mnt/share

      - name: Check Network Connectivity
        run: ping -c 4 10.70.0.74

      - name: Mount SMB Share
        run: |
          sudo mount -t cifs //10.70.0.74/s473603/public_iis /mnt/share -o username=${{ secrets.IIS_LOGIN }},password=${{ secrets.IIS_PASSWORD }},file_mode=0777,dir_mode=0777,vers=3.0
          echo 'Application offline for maintenance' > /mnt/share/$OFFLINE_FILE

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Debug

      - name: Publish Application
        run: pwd &&
             mkdir publish &&
             sudo chmod -R 777 ./publish &&
             dotnet publish --configuration Debug --output ./publish

      - name: Deploy to Network Share
        run: |
          sudo cp -r ./publish/* /mnt/share/
        
      - name: Cleanup
        run: |
          sudo rm /mnt/share/$OFFLINE_FILE
          
      - name: Unmount SMB Share
        run: sudo umount /mnt/share

      - name: Clean Up VPN Config File
        run: rm -f vpn-config.ovpn
