name: Webio WebDeploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish --no-build

    - name: Deploy using WebDeploy
      env:
        DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
      run: |
        msdeploy.exe -verb:sync -source:package='./publish/EuroCarsUSA.zip' -dest:auto,computerName='https://ssl3.webio.pl:8172/msdeploy.axd?site=eurocarusa.eu',userName='eurocarusa.eu_naszhu',password='${{ secrets.DEPLOY_PASSWORD }}',authType='Basic' -allowUntrusted
